---
include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"
require: []
domains: []
reporters:
- rubocop
- require_not_found
- typecheck:strict
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths:
  - 'koans'
plugins: []
max_files: 5000
